import argparse
import json
from pathlib import Path
import statistics
import sys
import unittest

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

import numpy as np

from evaluation.benchmark import markdown as benchmark_markdown
from evaluation.report import markdown_report, validate_suite
from scripts.validation_docs import documents


def audit() -> tuple[str, list[str]]:
    suite = json.loads((ROOT / "evaluation/results.json").read_text(encoding="utf-8"))
    benchmark = json.loads((ROOT / "evaluation/benchmark_results.json").read_text(encoding="utf-8"))
    validate_suite(suite)
    metrics = suite["metrics"]
    baseline = metrics["final_shape_dtype_baseline"]
    generated = {**documents(), "evaluation/results.md": markdown_report(suite),
                 "evaluation/benchmark_results.md": benchmark_markdown(benchmark)}
    failures = [name + " differs from its source artifact" for name, value in generated.items()
                if (ROOT / name).read_text(encoding="utf-8") != value]
    rows = [
        ("Synthetic fixtures", "evaluation/results.json: fixture_count", str(suite["fixture_count"])),
        ("Cases per run", "evaluation/results.json: metrics", str(metrics["cases_evaluated"])),
        ("Supported defects detected", "evaluation/results.json: metrics", f"{metrics['defects_detected']}/{metrics['defect_cases']}"),
        ("First-boundary localization", "evaluation/results.json: metrics.boundary_localization", f"{metrics['boundary_localization']['correct']}/{metrics['boundary_localization']['total']}"),
        ("Supported classifications", "evaluation/results.json: metrics.supported_classification", f"{metrics['supported_classification']['correct']}/{metrics['supported_classification']['total']}"),
        ("Clean controls passed", "evaluation/results.json: metrics", f"{metrics['clean_controls_passed']}/{metrics['clean_cases']}"),
        ("Clean false positives", "evaluation/results.json: metrics", f"{metrics['clean_false_positives']}/{metrics['clean_cases']}"),
        ("Final shape/dtype baseline detects", "evaluation/results.json: metrics.final_shape_dtype_baseline", f"{baseline['naive_defects_detected']}/{baseline['defective_cases']}"),
        ("Semantic repeatability", "evaluation/results.json: metrics.reproducibility", f"{metrics['reproducibility']['runs']} runs; match={metrics['reproducibility']['matched']}"),
        ("Current test inventory", "unittest discovery; executed by final_review.py", str(unittest.defaultTestLoader.discover(str(ROOT), top_level_dir=str(ROOT)).countTestCases())),
        ("Recorded hardening tests", "docs/PREFLIGHT.json (earlier run)", "20; historical record, not the current suite count"),
        ("Benchmark repetitions", "evaluation/benchmark_results.json", f"{benchmark['runs_per_scenario']} measured + {benchmark['warmup_per_scenario']} warmups per scenario"),
    ]
    for record in benchmark["records"]:
        if len(record["samples"]) != benchmark["runs_per_scenario"]:
            failures.append("Benchmark sample count: " + record["scenario"])
        for component, summary in record["summary"].items():
            samples = [sample[component] for sample in record["samples"]]
            expected = {"median_ms": round(statistics.median(samples), 3),
                        "p95_ms": round(float(np.percentile(samples, 95)), 3)}
            if summary != expected:
                failures.append("Benchmark summary: " + record["scenario"] + "/" + component)
            rows.append((record["scenario"] + " / " + component,
                         "evaluation/benchmark_results.json: samples", f"{expected['median_ms']:.3f} / {expected['p95_ms']:.3f} ms median/p95"))
    readme = " ".join((ROOT / "README.md").read_text(encoding="utf-8").split())
    phrases = (f"{metrics['cases_evaluated']}-case matrix", f"detects {metrics['defects_detected']}/{metrics['defect_cases']} defects",
               f"localizes {metrics['boundary_localization']['correct']}/{metrics['boundary_localization']['total']} first",
               f"classifies {metrics['supported_classification']['correct']}/{metrics['supported_classification']['total']} supported",
               f"passes all {metrics['clean_controls_passed']} clean controls", f"detects {baseline['naive_defects_detected']}/{baseline['defective_cases']}",
               f"set has {suite['fixture_count']} RGB PNGs")
    failures += ["README claim missing: " + phrase for phrase in phrases if phrase not in readme]
    lines = ["# Claims audit", "", "Generated by `python scripts/claims_audit.py --write` from measured artifacts and test discovery.", "",
             "| Claim | Source | Verified value | Status |", "|---|---|---|---|"]
    lines += [f"| {claim} | `{source}` | {value} | Source checked |" for claim, source, value in rows]
    lines += ["", "## Coverage and limits", "",
              "Exact regeneration checks cover evaluation/results.md, evaluation/benchmark_results.md, docs/VALIDATION.md and docs/SUBMISSION_FACTS.md. Benchmark summaries are recomputed from saved samples; no new timing measurements are inferred.",
              "README's major numeric phrases are checked automatically. app.py renders stage counts from executed results; evaluation/ui.py renders all six summary metrics from validated results.json. AppTest checks the displayed metrics and scenario states.",
              "Manual review covers README, app copy, all docs (including the submission draft, Q&A and recording plans), recorded environment/preflight JSON, and both evaluation outputs. Dates, commit hashes, dimensions, tolerances, command flags and presentation timestamps are context, not accuracy claims. The earlier 20-test preflight is retained as historical evidence; current execution is recorded in FINAL_VALIDATION.md.",
              "All detection and false-positive figures describe this contract-constrained synthetic set. Supported classifications are not proof of automatic root-cause diagnosis. Timings describe the recorded Windows environment and exclude startup, imports, workspace setup, rendering and the normal core --verify call.",
              "The five stages and four Bob session screenshots are checked by integrity/preflight. Only the original RGB/BGR repair is attributed to the recorded IBM Bob IDE workflow; the web app does not invoke Bob. Human reviewers must recheck free-form prose after future edits; this script is not a general semantic claim verifier.", ""]
    return "\n".join(lines), failures


def check_claims() -> str:
    content, failures = audit()
    if (ROOT / "docs/CLAIMS_AUDIT.md").read_text(encoding="utf-8") != content:
        failures.append("CLAIMS_AUDIT.md is stale; run python scripts/claims_audit.py --write")
    if failures:
        raise ValueError("; ".join(failures))
    return "Generated documents, README metrics and all saved benchmark summaries agree with source artifacts"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--write", action="store_true")
    args = parser.parse_args()
    if args.write:
        content, failures = audit()
        if failures:
            raise ValueError("; ".join(failures))
        (ROOT / "docs/CLAIMS_AUDIT.md").write_text(content, encoding="utf-8")
    print(check_claims())
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
