from datetime import datetime, timezone
import importlib.metadata
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PURPOSES = {"numpy": "Array storage, arithmetic, comparison and timing statistics",
            "pillow": "Trusted RGB image decoding and synthetic PNG generation",
            "opencv-python-headless": "Independent serving/candidate preprocessing without desktop GUI",
            "streamlit": "Local single-page demonstration and UI tests"}


def main() -> None:
    packages = []
    for name, purpose in PURPOSES.items():
        distribution = importlib.metadata.distribution(name)
        metadata = distribution.metadata
        license_value = metadata.get("License-Expression") or metadata.get("License")
        if not license_value:
            license_value = "Not specified in installed package metadata"
        elif len(license_value) > 200:
            license_value = "Long license text in installed metadata; see distribution license files"
        packages.append({"name": name, "version": distribution.version, "purpose": purpose,
                         "license_metadata": license_value.strip(),
                         "license_files": metadata.get_all("License-File") or []})
    document = {"generated_at": datetime.now(timezone.utc).isoformat(), "packages": packages,
                "source": "Installed distribution metadata; direct dependencies only, not a full transitive license or vulnerability audit."}
    (ROOT / "docs/dependencies.json").write_text(json.dumps(document, indent=2) + "\n", encoding="utf-8")
    lines = ["# Data and dependencies", "",
             "Original and evaluation image inputs are project-generated synthetic data.",
             "No external photographs, client/private datasets, social-media data, or model-training data are used.",
             "Original generation lives in protected fixtures/generate_fixtures.py; the 15-image set is generated by evaluation/fixtures.py.",
             "Evaluation metadata records its fixed seed, probe policy, pixel hashes, and PNG hashes.",
             "Bob session screenshots are user-supplied IDE workflow evidence, not evaluation input data; review them before publishing.", "",
             "| Installed package | Version | Purpose | License reported by metadata |", "|---|---|---|---|"]
    for package in packages:
        lines.append(f"| {package['name']} | {package['version']} | {package['purpose']} | {package['license_metadata']} |")
    lines += ["", document["source"], "Missing license metadata is not inferred. See dependencies.json and installed distribution license files for detail.",
              "Bundled native libraries may have additional notices. This inventory is not a legal conclusion about redistribution.",
              "Project/repository licensing and screenshot publication rights should be confirmed by the team before public release.", ""]
    (ROOT / "docs/DATA_AND_DEPENDENCIES.md").write_text("\n".join(lines), encoding="utf-8")


if __name__ == "__main__":
    main()
